version: '3'

services:
  tests:
    container_name: rdict-tests
    image: qas:latest
    volumes:
      - .:/app
    entrypoint: python -m pytest -ra -x -q --cov=tests --cov=rdict --cov-report term-missing --cov-report xml
  
  black-linter:
    container_name: rdict-linter
    image: qas:latest
    volumes:
      - .:/app
    entrypoint: python -m black .
